### ISSUE TITLE
doesnt seem to work at all

### ISSUE THREAD

**Issue by jeacott1** [shihanng/tfvar#12]
I was really hopeful about this tool, but it doesn't work at all on any of the terraform I've tried it with.
it doesn't seem to recurse directories, and it only looks for specific filenames, so if I'm looking at an unfamiliar project that's not using the convention expected here I've got to go and manually parse the project anyway.

I tried it against this repo https://github.com/kbst/terraform-kubestack
and even if I specifically specify a file known to contain variables, it throws an error. 
eg:
```
 tfvar . -d --var-file .terraform/modules/aks_zero/google/_modules/gke/variables.tf
2021-10-09T15:06:36.020+1030    DEBUG   cmd/cmd.go:89   Logger initialized
Error: tfvar: failed to get attributes: .terraform/modules/aks_zero/google/_modules/gke/variables.tf:1,1-9: Unexpected "variable" block; Blocks are not allowed here.
```

ideally I would type tfvars . and I'd get output of all the sources linked from the current project - worst case all the files in all the subdirectories!

**Comment by shihanng** [comment]
Closing. Please feel free to reopen the issue if the above does not work. Thank you.
