### ISSUE TITLE
goreleaser not building for arm arm64

### ISSUE THREAD

**Issue by disaac** [shihanng/tfvar#16]
Currently the goreleaser config is only building for amd64/386 for darwin/windows/linux os. In order to support modern macos arm64 hardware binaries should additionally be built for those as well. 

As a side effect the produced brew formula tap generated by goreleaser results in an error if installed on an arm64 mac. 

```
brew readall
Error: Invalid formula: /opt/homebrew/Library/Taps/shihanng/homebrew-tfvar/tfvar.rb
formulae require at least a URL
```

This is due to a URL missing for the arch in the formula. 

```
 on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shihanng/tfvar/releases/download/v0.4.1/tfvar_darwin_amd64.tar.gz"
      sha256 "3aa5a68097fbf7a7bc3de2ff02554481ce60d8e9514a3ced5ef6c3f6fa193f34"

      def install
        bin.install Dir['tfvar']
      end
    end
  end
```

**Comment by shihanng** [comment]
Close in #17
