### ISSUE TITLE
add flag to output variables as tfe_variable resource, or tfe_variable api payload

### ISSUE THREAD

**Issue by abuxton** [shihanng/tfvar#18]
I would like to add two flags;

-r --resource, which outputs variables as https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/resources/variable and can be piped to a .tf file for usage

-w --workspace, which outputs https://www.terraform.io/docs/cloud/api/workspace-variables.html#sample-payload format of each var, and can be piped to an individual file per var so to be able to upload as payload from curl request.

**Comment by shihanng** [comment]
I think these are great ideas. PRs are welcome!
