### ISSUE TITLE
Moved block being added to tfvars

### ISSUE THREAD

**Issue by ilfox** [shihanng/tfvar#22]
@shihanng from terraform version 1.1 hashicorp introduced the _moved_ block in order to rename resources (see [here](https://www.terraform.io/language/modules/develop/refactoring#moved-block-syntax)) It seems that this being added to the tfvars;
`Error: tfvar: loading config: main.tf:1,1-6: Unsupported block type; Blocks of type "moved" are not expected here.
`
P.S. When adding the moved block manually in main.tf after the image is built, the plan works as expected.

**Comment by shihanng** [comment]
Had a look into this. I can't simply do `go get -u` upgrade to support Terraform 1.0 due to the change in https://github.com/hashicorp/terraform/pull/28723.

**Comment by ilfox** [comment]
Ok thanks @shihanng. I look forward to your findings.

**Comment by shihanng** [comment]
@ilfox I have an open PR for this. Feel free to test it.
https://github.com/shihanng/tfvar/pull/23

**Comment by ilfox** [comment]
Perfect, it works @shihanng! Thanks a lot for quick the resolution.
