### ISSUE TITLE
Does not yet support sensitive = true flag

### ISSUE THREAD

**Issue by josefsalyer** [shihanng/tfvar#8]
**Expected Behavior**
Given a `variables.tf` file like
```
variable "password" {
  type        = string
  description = "the root password to use with the database"
  sensitive   = true
}
```
When I run the `tfvar` command
Then password variable is printed to stdout

**Actual Behavior**

An error is printed and processing of the variables file stops:
```
Error: tfvar: loading config: variables.tf:4,3-12: Unsupported argument; An argument named "sensitive" is not expected here.
```

**Comment by shihanng** [comment]
Thank you for reporting this issue. We've fixed this in #9 and will release this soon.
